In [3]:
import numpy as np

In [11]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [15]:
b=np.array([[1],[2],[3],[4],[5]])
print(b)
print(type(b))
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
<class 'numpy.ndarray'>
(5, 1)


In [22]:
c=np.array([[1,2,3],[4,5,6],[7,8]])
print(c.shape)
print(c[2][1])

(3,)
8


In [40]:
#array of zeros
a=np.zeros((3,3)) #Passing shape in arguments
print(a)
print(type(a))
#Array of ones
b=np.ones((1,5))
print(b)
#Array of constants
c=np.full((2,2),69)
print(c)
#IDentity matrix - Size/square matrix
IM=np.eye(4)
print(IM)
#Random Matrix
randomMatrix=np.random.random((5,5))
print(randomMatrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
[[1. 1. 1. 1. 1.]]
[[69 69]
 [69 69]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[2.24351936e-01 4.45991565e-01 6.44731505e-01 6.95349946e-01
  9.26483856e-01]
 [3.88722545e-02 4.51139842e-01 9.62066981e-01 3.20576340e-01
  9.68432979e-01]
 [8.64727149e-01 8.97929730e-01 6.95248983e-01 4.86478557e-01
  7.32646086e-01]
 [7.76084978e-01 2.83200748e-01 3.07292183e-01 3.84249738e-01
  5.94673941e-01]
 [8.11476785e-01 9.51487313e-01 7.31280430e-01 8.26160035e-05
  6.43507572e-01]]


In [45]:
print(randomMatrix[2:4,:2]) # [row,column] => [start:end+1,start,end+1] Slicing operation

[[0.86472715 0.89792973]
 [0.77608498 0.28320075]]


In [52]:
z=np.zeros((3,3),dtype=np.int64)
z[1,:]=5
z[:,-1]=7
print(z)

[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [53]:
#DATATYPE
print(z.dtype)

int64


In [58]:
#MAthematical Operations-Add,subtract,multiply,divide,sqrt
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x+y)
# OR
print(np.add(x,y))
print(y-x)

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[4 4]
 [4 4]]


In [60]:
print(x*y)
print(y/x)
print(np.sqrt(y))

[[ 5 12]
 [21 32]]
[[5.         3.        ]
 [2.33333333 2.        ]]
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [61]:
# Matrix Mutiplication
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [65]:
# Muliplication of vector => Returns scalar
a=np.array([1,2,3,4])
b=np.array([5,6,7,2])
print(a.dot(b))

46


In [69]:
#Sum of elements of an array
x=np.array([[1,2],[3,4]])
print(np.sum(x,axis=1))
print(sum(x))#By default row-wise

[3 7]
[4 6]


In [4]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.stack((a,b),axis=0)
print(np.stack((a,b),axis=1))
print(np.stack((a,b)))#by default axis=0

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [8]:
#Reshape an array => Put -1 where cols or rows are unknown
c=c.reshape((8,))# Reshaped to linear array
#d=np.reshape(c,(8,))
print(c)

[1 2 3 4 5 6 7 8]
